blog/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    #app
    path('',include('core.urls')),
    path('',include('usuario.urls')),
    path('',include('post.urls')),
]


if settings.DEBUG == True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from core.views import index,contatos

app_name = 'core'

urlpatterns = [
    path('', index,name='index'),
    path('contatos',contatos,name='contatos'),
]

post/urls.py
from django.urls import path
from post.views import PostListView,PostCreateView, PostDeleteView,PostUpdateView

app_name = 'post'

urlpatterns = [
    path('posts',PostListView.as_view(),name="listaposts"),
    path('criarposts',PostCreateView.as_view(),name="criarpost"),
    path('posts/<int:pk>/apagar',PostDeleteView.as_view(),name="deletarpost"),
    path('posts/<int:pk>/update',PostUpdateView.as_view(),name="updatepost")
]

usuario/urls.py
from django.urls import path
from usuario.views import UserListView,UserCreateView,UserDeleteView,UserUpdateView,UserDetailView,UserLoginView,UserLogoutView

app_name = 'usuario'

urlpatterns = [
   path('usuario',UserListView.as_view(),name="lista"),
   path('criarusuario',UserCreateView.as_view(),name="criar"),
   path('usuario/<int:pk>/apagar',UserDeleteView.as_view(),name="deletaruser"),
   path('usuario/<int:pk>/update',UserUpdateView.as_view(),name="updateuser"),
   path('usuario/<int:pk>/detalhes',UserDetailView.as_view(),name="detalhesuser"),
   path('usuario/login',UserLoginView.as_view(),name="loginuser"),
   path('usuario/logout',UserLogoutView.as_view(),name="logoutuser"),
   

]

core/models.py
from django.db import models

# Create your models here.

post/models.py
from django.db import models
from usuario.models import User
# Create your models here.

class Post(models.Model):
    
    autor = models.ForeignKey(User, on_delete = models.CASCADE,verbose_name='autor',related_name='posts')
    conteudo = models.TextField(verbose_name='contDDDSeudo',default="",max_length=280)
    data = models.DateTimeField(verbose_name='Data',auto_now_add=True)
    imagem = models.ImageField(upload_to="posts/")
    class Meta:
        verbose_name = 'Postagem'
        verbose_name_plural = 'Postagens'

    def __str__(self):
        return f'Autor: {self.autor} |  Data: {self.data} | ID: {self.id}'

    

usuario/models.py
from django.db import models
from django.contrib.auth.models import  AbstractUser

# Create your models here.

class User(AbstractUser):
    email = models.EmailField(unique=True)
    
    

post/forms.py
from django.contrib.auth.forms import UserCreationForm
from post.models import Post
from django import forms

class CreatePostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['autor','conteudo','imagem']

usuario/forms.py
from django.contrib.auth.forms import UserCreationForm
from usuario.models import User

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','email']

core/views.py
from django.shortcuts import render

# Create your views here.


def index(request):
    context={
        'pj':' poli junior',
    }
    return render(request,'core/index.html',context)

def contatos(request):
    context={
        'jean': 'JEÂNUS',
        'na':'LJLJLAJSLSFLAFSLF',
    }
    return render(request,'core/contato.html',context)

post/views.py
from django.shortcuts import render
from post.models import Post
from django.views.generic import ListView,CreateView,DeleteView,UpdateView
from post.forms import CreatePostForm
from django.urls import reverse_lazy
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.

class PostListView(ListView):
    model = Post
    context_object_name = 'posts'
    template_name = 'Post/posts.html'


class PostCreateView(LoginRequiredMixin,generic.CreateView):
    model = Post
    template_name = 'Post/createPost.html'
    form_class = CreatePostForm
    success_url = reverse_lazy('post:listaposts')

class PostDeleteView(LoginRequiredMixin,DeleteView):
    model = Post
    template_name = 'Post/delete.html'
    context_object_name = 'posts'
    success_url = reverse_lazy('post:listaposts')

class PostUpdateView(LoginRequiredMixin,UpdateView):
    model = Post
    fields = ['autor','conteudo','imagem']
    template_name = 'Post/update.html'
    success_url = reverse_lazy('post:listaposts')

usuario/views.py
from django.shortcuts import render
from usuario.models import User
from django.views.generic import ListView,CreateView,DeleteView,UpdateView,DetailView
from usuario.forms import CreateUserForm
from django.urls import reverse_lazy
from django.contrib.auth.views import LoginView,LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin


# Create your views here.

class UserListView(ListView):
    model = User
    context_object_name = 'users'
    template_name = 'Usuario/usuario.html'

class UserCreateView(CreateView):
    model = User
    template_name = 'Usuario/create.html'
    form_class = CreateUserForm
    success_url = reverse_lazy('usuario:lista')

class UserDeleteView(DeleteView):
    model = User
    template_name = 'Usuario/delete.html'
    context_object_name = 'delete'
    success_url = reverse_lazy('usuario:lista')

class UserUpdateView(UpdateView):
    model = User
    fields = ['username','email','password']
    template_name = 'Usuario/update.html'
    success_url = reverse_lazy('usuario:lista')

class UserDetailView(DetailView):
    model = User
    template_name = 'Usuario/detalhes.html'
    context_object_name = 'user'

class UserLoginView(LoginView):
    template_name = 'Usuario/login.html'

class UserLogoutView(LoginRequiredMixin,LogoutView):
    pass 

templates/Post/createPost.html
{% load widget_tweaks %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <div id="div">
    <form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <p> Autor : {% render_field form.autor %}</p>
    <p> Conteudo : {% render_field form.conteudo %}</p>
    <p> Selecione a imagem: {% render_field form.imagem %}</p>
    <input type="submit" value="Postar">
    </form>
</div>
</body>


<style>

    *{
        margin: 0;
        padding: 0;
    }


    #div{

        display: flex;
        width: 100%;
        min-height: 100vh;
        align-items: center;
        justify-content: space-around;
    }

    textarea{
        resize: none;
    }
</style>
</html>

templates/Post/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div class="intaum">
    <form action="" method="post">
        {% csrf_token%}
        {{form.as_p}}
        <input type="submit" value="Deletar"> 
    </form>
    </div>
</body>

<style>
    *{
        margin:0;
        padding:0;
    }
    .intaum{
        display: flex;
        justify-content: space-around;
        align-items: center;
        min-height: 100vh;
    }
</style>
</html>

templates/Post/posts.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>

    <div id="navbar">
        <a href="http://127.0.0.1:8000"><button>Voltar</button></a>
        <ul>
            {% if not request.user.is_authenticated %}
            <li><a href="{% url 'usuario:loginuser' %}"> Login</a></li> 
            <li>||<a href="{% url 'usuario:criar' %}"> Sign up</a></li> 
            {% else %}
            <li>Olá, <a href="{% url 'usuario:detalhesuser' request.user.id %}"> {{ request.user.username }}</a></li> 
            <li> || <a href="{% url 'usuario:logoutuser' %}"> Logout</a></li> 
            {% endif %}
        </ul>
    </div>

    <h1>POSTS</h1>
    
    <div class="posts">
    {% for user in posts%}
    <div class="card">
    <p class="autor">Autor: {{user.autor}}</p>
    <p class="conteudo">"{{user.conteudo}}"</p>
    <p class="data">Data: {{user.data}}</p>
    <img id="imagem" src="{{user.imagem.url}}">
    <a href="http://127.0.0.1:8000/posts/{{user.id}}/apagar"><button>apagar</button></a>
    <a href="http://127.0.0.1:8000/posts/{{user.id}}/update"><button>alterar</button></a>
    </div>
    {%endfor%}

    <a href="http://127.0.0.1:8000/criarposts"><button>Criar nova postagem</button></a>
    </div>
</body>

<style>

    h1{
        text-align: center;
    }
    .posts{
        display: flex;
        flex-wrap: wrap;
        flex-direction: column;
        align-items: center;
        justify-content: space-around;
    }
.card{
    display: flex;
    justify-content: space-around;
    align-items: center;
    flex-direction: column;
    border-radius: 8px;
    border-style: groove;
    box-shadow: black;
    text-align: center;
    background-color:rgba(211, 178, 137, 0.808);
    width: 80%;
    box-sizing: border-box;
    word-wrap: break-word;
    padding: 1%;
    margin-bottom: 2%;
}

.autor{
    font-weight: bold;
    font-size: large;

}

#imagem{
    width: 50%;
    height: 50%;
    margin-bottom: 2%;
}

li{
    display: inline;
}
</style>
</html>

templates/Post/update.html
{% load widget_tweaks %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div class="intaum">
    <form action="" method="post">
        {% csrf_token%}
        <p> Autor : {% render_field form.autor %}</p>
        <p><div class="conteudo"> Conteudo : {% render_field form.conteudo %}</div></p>
        <p> Selecione a imagem: {% render_field form.imagem %}</p>
        <input type="submit" value="Alterar"> 
    </form>
    </div>
</body>

<style>
    *{
        margin:0;
        padding:0;
    }
    .intaum{
        display: flex;
        justify-content: space-around;
        align-items: center;
        min-height: 100vh;
    }

    .conteudo textarea{
        resize: none;
    }
</style>
</html>

templates/Usuario/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>

    <h1>CRIAR USUARIO</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Enviar">
    </form>
</body>
</html>

templates/Usuario/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div class="intaum">
    <form action="" method="post">
        {% csrf_token%}
        {{form.as_p}}
        <input type="submit" value="Deletar"> 
    </form>
    </div>
</body>

<style>
    *{
        margin:0;
        padding:0;
    }
    .intaum{
        display: flex;
        justify-content: space-around;
        align-items: center;
        min-height: 100vh;
    }
</style>
</html>

templates/Usuario/detalhes.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <a href="http://127.0.0.1:8000/usuario"><button>Voltar</button></a><h1>DETALHES DO USUARIO</h1>
    <div class="posts">
    
    <div class="card">
    <div><strong>Username: </strong>{{user.username}}</div>
    <div><strong>Email: </strong>{{user.email}}</div>
    <div><strong>Last login: </strong>{{user.last_login}}</div>
    </div>
    <h1>POSTAGENS</h1>
    
    {% for users in user.posts.all%}
    <div class="card">
    <div><strong>"{{users.conteudo}}"</strong></user></div>
    <div> <img src="{{users.imagem.url}}" ></div>
    <div> Data: {{users.data}}</div>
    </div>
    {%endfor%}

    
    

    </div>
</body>

<style>
    h1{
    text-align: center;
}
.posts{
    display: flex;
    flex-wrap: wrap;
    flex-direction: column;
    align-items: center;
    justify-content: space-around;
}
.card{
display: flex;
justify-content: space-around;
align-items: center;
flex-direction: column;
border-radius: 8px;
border-style: groove;
box-shadow: black;
text-align: center;
background-color:rgba(211, 178, 137, 0.808);
width: 80%;
box-sizing: border-box;
word-wrap: break-word;
padding: 1%;
margin-bottom: 2%;
}

</style>
</html>

templates/Usuario/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
    <form action="" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Logar">
    </form>
</body>
</html>

templates/Usuario/update.html
{% load widget_tweaks %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div class="intaum">
    <form action="" method="post">
        {% csrf_token%}
        {{form.as_p}}
        <!--
        <p> Altere seu usuario : {% render_field form.username %}</p>
        <p><div class="conteudo"> Altere seu email : {% render_field form.email %}</div></p>
        <p> Altere sua senha: {% render_field form.password %}</p>
        <input type="submit" value="Alterar"> -->
    </form>
    </div>
</body>

<style>
    *{
        margin:0;
        padding:0;
    }
    .intaum{
        display: flex;
        justify-content: space-around;
        align-items: center;
        min-height: 100vh;
    }

    .conteudo textarea{
        resize: none;
    }
</style>
</html>

templates/Usuario/usuario.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <a href="http://127.0.0.1:8000"><button>Voltar</button></a><h1>USUARIOS</h1>
    <div class="posts">
    {% for user in users%}
    <div class="card">
    <div>Username: {{user.username}}</div>
    <div>Email: {{user.email}}</div>
    <div>Last login: {{user.last_login}}</div>
    <a href="http://127.0.0.1:8000/usuario/{{user.id}}/detalhes"><button>Detalhes</button></a>
    <a href="http://127.0.0.1:8000/usuario/{{user.id}}/update"><button>alterar</button></a>
    <a href="http://127.0.0.1:8000/usuario/{{user.id}}/apagar"><button>apagar</button></a>
    
    </div>
    {%endfor%}

    <a href="http://127.0.0.1:8000/criarusuario"><button>Criar novo user</button></a>
    </div>
</body>

<style>
        h1{
        text-align: center;
    }
    .posts{
        display: flex;
        flex-wrap: wrap;
        flex-direction: column;
        align-items: center;
        justify-content: space-around;
    }
.card{
    display: flex;
    justify-content: space-around;
    align-items: center;
    flex-direction: column;
    border-radius: 8px;
    border-style: groove;
    box-shadow: black;
    text-align: center;
    background-color:rgba(211, 178, 137, 0.808);
    width: 80%;
    box-sizing: border-box;
    word-wrap: break-word;
    padding: 1%;
    margin-bottom: 2%;
}

</style>
</html>

templates/core/contato.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1>CONTATOS {{jean}} {{na}}</h1>
    <a href="{% url 'core:index' %}">AAAAA</a>
</body>
</html>

templates/core/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <a href="http://127.0.0.1:8000/usuario"><h1>USUARIOS</h1></a>
    <a href="http://127.0.0.1:8000/posts"><h1>POSTS</h1></a>
</body>
</html>